services:
  docs:
    image: yfiles_local_docs
    container_name: yfiles_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./yfiles:/app/yfiles:z
    ports:
      - '9000:9000'
    command: /start-docs
