# Generated by Django 5.0.9 on 2024-10-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_link", models.URLField(max_length=255)),
                ("path", models.CharField(max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("type", models.CharField(max_length=50)),
                ("mime_type", models.CharField(max_length=100)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Preview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_name", models.CharField(max_length=10)),
                ("preview_url", models.URLField(max_length=1024)),
            ],
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("public_link", "name"), name="unique_public_link_name"
            ),
        ),
        migrations.AddField(
            model_name="preview",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previews",
                to="yd_files.file",
            ),
        ),
    ]
